#Make sure you have gcc version 9.1 or higher to benefit from c++17 language
#You can check current version by running <gcc --version>

ExprTree: ExprTree.cpp
	g++ -std=c++17 ExprTree.cpp -o ExprTree
